/*
 * This source file was generated by the Gradle 'init' task
 */
package belajar.gradle

import com.google.gson.Gson
import org.example.StringUtil
import product

class App {
    val greeting: String
        get() {
            return "Hello World!" + " Belajar Kotlin"
        }
}

fun main() {
    println(App().greeting)
    println("Aku Kaya")

    val gson = Gson()
    println(gson.toJson(App().greeting))

    val product1 = product("1", "HandPhone Ipun")
    println(StringUtil.toUpper(product1.name))

}
